# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core



pool:
  vmImage: 'ubuntu-latest'

 

steps:

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    vstsFeed: '7874d177-1888-4cd8-bf0f-b194a953da73'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'off'

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
  
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.104'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'    

variables:
buildConfiguration: 'Release'
  
- script: 'dotnet build --configuration $(buildConfiguration)'
  displayName: 'dotnet build $(buildConfiguration)' 




